### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gyng** [gyng/save-in#142]
If you're reading this, you're probably a user of save-in. I'm really busy at my day job, but I do have plans for the extension. Progress is expected to be slow until things ease up at work. PRs welcome!

## Chores

The extension was originally just something I needed for the FF Photon update but has grown way beyond what I imagined it to be. Will need cleanup for more sustainable development.

- [ ] Add type annotations to the code
- [ ] Refactor to TypeScript using https://github.com/gyng/webext-boilerplate/
- [ ] Move to `chrome.onDeterminingFilename` for Firefox (needs https://bugzilla.mozilla.org/show_bug.cgi?id=1245652)
- [ ] Rewrite options page using a library (Preact?)

## Features

Some I'd like done, in rough order of priority

- [ ] Add more last used entries #122 
- [ ] Allow for integrations with other APIs #110
- [ ] Per-site prefer links option #100
- [ ] Undo last save #102

**Comment by gyng** [comment]
Closing this old planning tracker as superseded by the [repository roadmap](https://github.com/gyng/save-in/blob/master/docs/project/ROADMAP.md). [Save In 4.1.0](https://github.com/gyng/save-in/releases/tag/v4.1.0) includes the TypeScript rewrite, recent destinations, external integrations, per-site link preferences, and History Undo. Remaining design decisions and browser constraints are tracked in the repository documentation and their specific issues.
